[project]
name = "single-site-collect-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aind-behavior-vr-foraging[launcher]>=0.6.0",
    "aind-data-access-api[docdb]>=1.9.2",
]
